export const USER_ROLES = ["basic", "leader", "admin", "sdr"];
export const USER_SECTORS = [
  "CS",
  "Comercial",
  "Financeiro",
  "Desenvolvimento",
  "Suporte",
  "Implantacao",
];

export const DEFAULT_SECTORS = USER_SECTORS.map((name, index) => ({
  key: name.toUpperCase().replace(/[^A-Z0-9]+/g, "_"),
  name,
  description: `${name} do sistema`,
  sortOrder: (index + 1) * 10,
}));

export const CATALOG_TYPES = ["PRODUCT", "INTEGRATION"];
export const DOC_TYPES = ["CPF", "CNPJ"];
export const LEAD_STATUSES = [
  "Leads",
  "Qualificados",
  "Oportunidade Futura",
  "Apresentacao",
  "No Show",
  "Em Negociacao",
  "Ganho",
  "Perdido",
];
export const LEAD_TASK_TYPES = [
  "reuniao",
  "ligacao",
  "whatsapp",
  "email",
  "demo",
  "follow",
  "visita",
  "outro",
];
export const TICKET_STATUSES = [
  "pendente_financeiro",
  "pagamento_confirmado",
  "em_implantacao",
  "concluido",
  "cancelado",
];
export const TICKET_TYPES = ["novo", "upsell", "renovacao"];
export const ACCESS_LEVELS = ["none", "view", "edit", "manage"];

export const LEGACY_ROLE_ALIASES = {
  agent: "basic",
  supervisor: "leader",
  basic: "basic",
  leader: "leader",
  admin: "admin",
  sdr: "basic",
};

export const MODULE_KEYS = [
  "DASHBOARD",
  "DASHBOARD_CRM",
  "DASHBOARD_SUPORTE",
  "DASHBOARD_DEV",
  "COMMERCIAL",
  "CRM_VENDA",
  "CRM_TAREFAS",
  "CRM_PERDIDOS",
  "CLIENTES",
  "FINANCEIRO",
  "FINANCEIRO_COBRANCA",
  "FINANCEIRO_INDICADORES",
  "FINANCEIRO_FLUXO",
  "IMPLANTACAO",
  "IMPLANTACAO_KANBAN",
  "IMPLANTACAO_TAREFAS",
  "SUPORTE",
  "DESENVOLVIMENTO",
  "DEV_KANBAN",
  "DEV_SPRINTS",
  "DEV_BIBLIOTECA",
  "CADASTROS",
  "CADASTROS_INTEGRACOES",
  "CADASTROS_PRODUTOS",
  "CADASTROS_PLANOS",
  "CADASTROS_ETIQUETAS",
  "CADASTROS_ORIGENS",
  "CADASTROS_INDICADORES",
  "USUARIOS",
  "USUARIOS_GESTAO",
  "USUARIOS_PRESETS",
  "USUARIOS_SETORES",
  "LIXEIRA",
];

export const DEFAULT_MODULES = [
  { key: "DASHBOARD", name: "Dashboard", description: "Visao geral e indicadores", sortOrder: 10, scope: "MODULE" },
  { key: "DASHBOARD_CRM", name: "Dashboard CRM", description: "Indicadores comerciais", parentKey: "DASHBOARD", path: "/dashboardcrm", sortOrder: 11, scope: "PAGE" },
  { key: "DASHBOARD_SUPORTE", name: "Dashboard Suporte", description: "Indicadores de suporte", parentKey: "DASHBOARD", path: "/dashboardSuporte", sortOrder: 12, scope: "PAGE" },
  { key: "DASHBOARD_DEV", name: "Dashboard Dev", description: "Indicadores de desenvolvimento", parentKey: "DASHBOARD", path: "/dashboardDev", sortOrder: 13, scope: "PAGE" },
  { key: "COMMERCIAL", name: "Comercial", description: "Leads, CRM e negociacoes", sortOrder: 20, scope: "MODULE" },
  { key: "CRM_VENDA", name: "CRM de Venda", description: "Funis, leads e oportunidades", parentKey: "COMMERCIAL", path: "/comercial/crm-venda", sortOrder: 21, scope: "PAGE" },
  { key: "CRM_TAREFAS", name: "Tarefas dos Leads", description: "Acompanhamento operacional dos leads", parentKey: "COMMERCIAL", path: "/comercial/tarefas-leads", sortOrder: 22, scope: "PAGE" },
  { key: "CRM_PERDIDOS", name: "Leads Perdidos", description: "Consulta e analise de perdas", parentKey: "COMMERCIAL", path: "/comercial/leads-perdidos", sortOrder: 23, scope: "PAGE" },
  { key: "CLIENTES", name: "Clientes", description: "Base de clientes, contratos e historico da conta", path: "/clientes", sortOrder: 25, scope: "PAGE" },
  { key: "FINANCEIRO", name: "Financeiro", description: "Fluxo, cobranca e contratos", sortOrder: 30, scope: "MODULE" },
  { key: "FINANCEIRO_COBRANCA", name: "Cobranca e Contrato", description: "Cobranca, contratos e tickets financeiros", parentKey: "FINANCEIRO", path: "/financeiro/cobranca-contrato", sortOrder: 31, scope: "PAGE" },
  { key: "FINANCEIRO_INDICADORES", name: "Pagamento Indicadores", description: "Repasse e comissoes de indicadores", parentKey: "FINANCEIRO", path: "/financeiro/pagamento-indicadores", sortOrder: 32, scope: "PAGE" },
  { key: "FINANCEIRO_FLUXO", name: "Fluxo", description: "Fluxo financeiro consolidado", parentKey: "FINANCEIRO", path: "/financeiro/fluxo", sortOrder: 33, scope: "PAGE" },
  { key: "IMPLANTACAO", name: "Implantacao", description: "Tickets e acompanhamento de implantacao", sortOrder: 40, scope: "MODULE" },
  { key: "IMPLANTACAO_KANBAN", name: "Kanban Implantacao", description: "Operacao visual da implantacao", parentKey: "IMPLANTACAO", path: "/implantacao/kanban-implantacao", sortOrder: 41, scope: "PAGE" },
  { key: "IMPLANTACAO_TAREFAS", name: "Tarefas Implantadores", description: "Fila operacional dos implantadores", parentKey: "IMPLANTACAO", path: "/implantacao/tarefas-implantadores", sortOrder: 42, scope: "PAGE" },
  { key: "SUPORTE", name: "Suporte", description: "Atendimento e operacao de suporte", sortOrder: 50, scope: "MODULE" },
  { key: "DESENVOLVIMENTO", name: "Desenvolvimento", description: "Demandas e operacao tecnica", sortOrder: 60, scope: "MODULE" },
  { key: "DEV_KANBAN", name: "Kanban Dev", description: "Operacao do kanban de desenvolvimento", parentKey: "DESENVOLVIMENTO", path: "/desenvolvimento/kanban-dev", sortOrder: 61, scope: "PAGE" },
  { key: "DEV_SPRINTS", name: "Sprints", description: "Planejamento e execucao de sprints", parentKey: "DESENVOLVIMENTO", path: "/desenvolvimento/sprints", sortOrder: 62, scope: "PAGE" },
  { key: "DEV_BIBLIOTECA", name: "Biblioteca Dev", description: "Historico e consulta de entregas dev", parentKey: "DESENVOLVIMENTO", path: "/biblioteca-dev", sortOrder: 63, scope: "PAGE" },
  { key: "CADASTROS", name: "Cadastros", description: "Cadastros administrativos e configuracoes", sortOrder: 70, scope: "MODULE" },
  { key: "CADASTROS_INTEGRACOES", name: "Integracoes", description: "Gestao de integracoes", parentKey: "CADASTROS", path: "/integracoes", sortOrder: 71, scope: "PAGE" },
  { key: "CADASTROS_PRODUTOS", name: "Produtos", description: "Gestao de produtos", parentKey: "CADASTROS", path: "/produtos", sortOrder: 72, scope: "PAGE" },
  { key: "CADASTROS_PLANOS", name: "Planos", description: "Gestao de planos comerciais", parentKey: "CADASTROS", path: "/planos", sortOrder: 73, scope: "PAGE" },
  { key: "CADASTROS_ETIQUETAS", name: "Etiquetas", description: "Gestao de etiquetas", parentKey: "CADASTROS", path: "/etiquetas", sortOrder: 74, scope: "PAGE" },
  { key: "CADASTROS_ORIGENS", name: "Origens CRM", description: "Gestao de origens comerciais", parentKey: "CADASTROS", path: "/origens-crm", sortOrder: 75, scope: "PAGE" },
  { key: "CADASTROS_INDICADORES", name: "Indicadores", description: "Gestao de indicadores", parentKey: "CADASTROS", path: "/indicadores", sortOrder: 76, scope: "PAGE" },
  { key: "USUARIOS", name: "Usuarios", description: "Gestao de usuarios, cargos e acessos", sortOrder: 80, scope: "MODULE" },
  { key: "USUARIOS_GESTAO", name: "Usuarios", description: "Gestao dos usuarios do sistema", parentKey: "USUARIOS", path: "/usuarios", sortOrder: 81, scope: "PAGE" },
  { key: "USUARIOS_PRESETS", name: "Presets de Acesso", description: "Gestao de presets e matrizes de acesso", parentKey: "USUARIOS", path: "/usuarios", sortOrder: 82, scope: "PAGE" },
  { key: "USUARIOS_SETORES", name: "Setores", description: "Gestao dos setores disponiveis", parentKey: "USUARIOS", path: "/usuarios", sortOrder: 83, scope: "PAGE" },
  { key: "LIXEIRA", name: "Lixeira", description: "Itens excluidos com restauracao e exclusao permanente", path: "/lixeira", sortOrder: 90, scope: "PAGE" },
];

export const DEFAULT_ACTIONS = [
  { key: "view", label: "Visualizar", sortOrder: 10 },
  { key: "create", label: "Criar", sortOrder: 20 },
  { key: "edit", label: "Editar", sortOrder: 30 },
  { key: "delete", label: "Excluir", sortOrder: 40 },
  { key: "import", label: "Importar", sortOrder: 50 },
  { key: "export", label: "Exportar", sortOrder: 60 },
  { key: "approve", label: "Aprovar", sortOrder: 70 },
  { key: "conclude", label: "Concluir", sortOrder: 80 },
  { key: "manage", label: "Gerenciar", sortOrder: 90 },
];

export const SYSTEM_PRESET_DEFINITIONS = [
  {
    slug: "basic-commercial-view",
    name: "Basico Comercial",
    description: "Visualizacao do modulo comercial",
    role: "basic",
    modulePermissions: [
      { moduleKey: "DASHBOARD", accessLevel: "view" },
      { moduleKey: "COMMERCIAL", accessLevel: "view" },
      { moduleKey: "CRM_VENDA", accessLevel: "view" },
      { moduleKey: "CRM_TAREFAS", accessLevel: "view" },
      { moduleKey: "CRM_PERDIDOS", accessLevel: "view" },
      { moduleKey: "CLIENTES", accessLevel: "view" },
    ],
  },
  {
    slug: "basic-finance-view",
    name: "Basico Financeiro",
    description: "Visualizacao do modulo financeiro",
    role: "basic",
    modulePermissions: [
      { moduleKey: "DASHBOARD", accessLevel: "view" },
      { moduleKey: "FINANCEIRO", accessLevel: "view" },
      { moduleKey: "FINANCEIRO_COBRANCA", accessLevel: "view" },
      { moduleKey: "FINANCEIRO_INDICADORES", accessLevel: "view" },
      { moduleKey: "FINANCEIRO_FLUXO", accessLevel: "view" },
      { moduleKey: "CLIENTES", accessLevel: "view" },
    ],
  },
  {
    slug: "leader-commercial",
    name: "Lider Comercial",
    description: "Gerencia o modulo comercial e restaura itens da lixeira",
    role: "leader",
    modulePermissions: [
      { moduleKey: "DASHBOARD", accessLevel: "view" },
      { moduleKey: "COMMERCIAL", accessLevel: "manage" },
      { moduleKey: "CRM_VENDA", accessLevel: "manage" },
      { moduleKey: "CRM_TAREFAS", accessLevel: "manage" },
      { moduleKey: "CRM_PERDIDOS", accessLevel: "manage" },
      { moduleKey: "CLIENTES", accessLevel: "manage" },
      { moduleKey: "LIXEIRA", accessLevel: "edit" },
    ],
  },
  {
    slug: "leader-finance",
    name: "Lider Financeiro",
    description: "Gerencia o modulo financeiro e restaura itens da lixeira",
    role: "leader",
    modulePermissions: [
      { moduleKey: "DASHBOARD", accessLevel: "view" },
      { moduleKey: "FINANCEIRO", accessLevel: "manage" },
      { moduleKey: "FINANCEIRO_COBRANCA", accessLevel: "manage" },
      { moduleKey: "FINANCEIRO_INDICADORES", accessLevel: "manage" },
      { moduleKey: "FINANCEIRO_FLUXO", accessLevel: "manage" },
      { moduleKey: "CLIENTES", accessLevel: "view" },
      { moduleKey: "LIXEIRA", accessLevel: "edit" },
    ],
  },
  {
    slug: "leader-implantacao",
    name: "Lider Implantacao",
    description: "Gerencia implantacao e restaura itens da lixeira",
    role: "leader",
    modulePermissions: [
      { moduleKey: "DASHBOARD", accessLevel: "view" },
      { moduleKey: "IMPLANTACAO", accessLevel: "manage" },
      { moduleKey: "IMPLANTACAO_KANBAN", accessLevel: "manage" },
      { moduleKey: "IMPLANTACAO_TAREFAS", accessLevel: "manage" },
      { moduleKey: "CLIENTES", accessLevel: "view" },
      { moduleKey: "LIXEIRA", accessLevel: "edit" },
    ],
  },
  {
    slug: "leader-support",
    name: "Lider Suporte",
    description: "Gerencia suporte e restaura itens da lixeira",
    role: "leader",
    modulePermissions: [
      { moduleKey: "DASHBOARD", accessLevel: "view" },
      { moduleKey: "SUPORTE", accessLevel: "manage" },
      { moduleKey: "CLIENTES", accessLevel: "view" },
      { moduleKey: "LIXEIRA", accessLevel: "edit" },
    ],
  },
  {
    slug: "leader-development",
    name: "Lider Desenvolvimento",
    description: "Gerencia desenvolvimento e restaura itens da lixeira",
    role: "leader",
    modulePermissions: [
      { moduleKey: "DASHBOARD", accessLevel: "view" },
      { moduleKey: "DESENVOLVIMENTO", accessLevel: "manage" },
      { moduleKey: "DEV_KANBAN", accessLevel: "manage" },
      { moduleKey: "DEV_SPRINTS", accessLevel: "manage" },
      { moduleKey: "DEV_BIBLIOTECA", accessLevel: "manage" },
      { moduleKey: "CLIENTES", accessLevel: "view" },
      { moduleKey: "LIXEIRA", accessLevel: "edit" },
    ],
  },
];
